config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'game_windows#start'

  get 'game_windows/start'
  get 'game_windows/play'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_windows_controller.rb
class GameWindowsController < ApplicationController
  def start
  end

  def play
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_windows_helper.rb
module GameWindowsHelper
end

app/views/game_windows/play.html.erb
<%= image_tag 'play_game.jpg', class: 'play-image' %>

app/views/game_windows/start.html.erb
<div class="image-container">
  <%= link_to game_windows_play_path do %>
    <%= image_tag 'start_game.jpg', class: 'start-image' %>
  <% end %>
  <div class="button-overlay">
    <div class="start-button">DEBUG</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugs Shooter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <header>
    <%= link_to 'Bugs Shooter', game_windows_start_path %>
  </header>
  <body>
    <%= yield %>
  </body>
</html>